'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Administraciones
    Public Property idAdministrador As Integer
    Public Property primerNombre As String
    Public Property segundoNombre As String
    Public Property primerApellido As String
    Public Property segundoApellido As String
    Public Property rolAdministrador As String

End Class
