'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Asistencia
    Public Property idAsistencia As Integer
    Public Property fechaAsistencia As Nullable(Of Date)
    Public Property HoraEntrada As System.TimeSpan
    Public Property HoraSalida As System.TimeSpan
    Public Property idEmpleado As Nullable(Of Integer)

    Public Overridable Property Empleado As Empleado

End Class
