'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class BDSistemaEySEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=BDSistemaEySEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Asistencia() As DbSet(Of Asistencia)
    Public Overridable Property Cargo() As DbSet(Of Cargo)
    Public Overridable Property Departamento() As DbSet(Of Departamento)
    Public Overridable Property Empleado() As DbSet(Of Empleado)
    Public Overridable Property Grupos() As DbSet(Of Grupos)
    Public Overridable Property Horario() As DbSet(Of Horario)
    Public Overridable Property SolVacaciones() As DbSet(Of SolVacaciones)

End Class
