'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Departamento
    Public Property idDepartamento As Integer
    Public Property nombreDepartamento As String
    Public Property descripcionDepartamento As String
    Public Property extensionDepartamento As String

    Public Overridable Property Empleado As ICollection(Of Empleado) = New HashSet(Of Empleado)

End Class
