'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Empleado
    Public Property idEmpleado As Integer
    Public Property primerNombre As String
    Public Property segundoNombre As String
    Public Property primerApellido As String
    Public Property segundoApellido As String
    Public Property fechaIngreso As Nullable(Of Date)
    Public Property cedulaEmpleado As Nullable(Of Double)
    Public Property idCargo As Integer
    Public Property idDepartamento As Integer
    Public Property idHorario As Integer
    Public Property idGrupo As Integer

    Public Overridable Property Asistencia As ICollection(Of UserAttendance) = New HashSet(Of UserAttendance)
    Public Overridable Property Cargo As Cargo
    Public Overridable Property Departamento As Departamento
    Public Overridable Property SolVacaciones As ICollection(Of SolVacaciones) = New HashSet(Of SolVacaciones)
    Public Overridable Property Grupos As Grupos
    Public Overridable Property Horario As Horario

End Class
