'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Empleado
    Public Property idEmpleado As Integer
    Public Property primerNombre As String
    Public Property segundoNombre As String
    Public Property primerApellido As String
    Public Property segundoApellido As String
    Public Property fechaIngreso As Nullable(Of Date)
    Public Property cedulaEmpleado As String
    Public Property password As String
    Public Property idCargo As Nullable(Of Integer)
    Public Property idDepartamento As Nullable(Of Integer)
    Public Property idHorario As Nullable(Of Integer)
    Public Property idGrupo As Nullable(Of Integer)

    Public Overridable Property Asistencia As ICollection(Of Asistencia) = New HashSet(Of Asistencia)
    Public Overridable Property Cargo As Cargo
    Public Overridable Property Departamento As Departamento
    Public Overridable Property SolVacaciones As ICollection(Of SolVacaciones) = New HashSet(Of SolVacaciones)
    Public Overridable Property Grupos As Grupos
    Public Overridable Property Horario As Horario

End Class
