'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Horario
    Public Property idHorario As Integer
    Public Property lunesInicio As Nullable(Of System.TimeSpan)
    Public Property lunesSalida As Nullable(Of System.TimeSpan)
    Public Property martesInicio As Nullable(Of System.TimeSpan)
    Public Property martesSalida As Nullable(Of System.TimeSpan)
    Public Property miercolesInicio As Nullable(Of System.TimeSpan)
    Public Property miercolesSalida As Nullable(Of System.TimeSpan)
    Public Property juevesInicio As Nullable(Of System.TimeSpan)
    Public Property juevesSalida As Nullable(Of System.TimeSpan)
    Public Property viernesInicio As Nullable(Of System.TimeSpan)
    Public Property viernesSalida As Nullable(Of System.TimeSpan)
    Public Property sabadoInicio As Nullable(Of System.TimeSpan)
    Public Property sabadoSalida As Nullable(Of System.TimeSpan)
    Public Property domingoInicio As Nullable(Of System.TimeSpan)
    Public Property domingoSalida As Nullable(Of System.TimeSpan)

    Public Overridable Property Empleado As ICollection(Of Empleado) = New HashSet(Of Empleado)

End Class
