'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Horario
    Public Property idHorario As Integer
    Public Property lunesInicio As Date
    Public Property lunesSalida As Nullable(Of Date)
    Public Property martesInicio As Nullable(Of Date)
    Public Property MartesSalida As Nullable(Of Date)
    Public Property miercolesInicio As Nullable(Of Date)
    Public Property miercolesSalida As Nullable(Of Date)
    Public Property juevesInicio As Nullable(Of Date)
    Public Property juevesSalida As Nullable(Of Date)
    Public Property viernesInicio As Nullable(Of Date)
    Public Property viernesSalida As Nullable(Of Date)
    Public Property sabadoInicio As Nullable(Of Date)
    Public Property sabadoFin As Nullable(Of Date)
    Public Property domingoFin As Nullable(Of Date)
    Public Property domingoInicio As Nullable(Of Date)

    Public Overridable Property Empleado As ICollection(Of Empleado) = New HashSet(Of Empleado)

End Class
