'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SolVacaciones
    Public Property idSolVacaciones As Integer
    Public Property fechaSol As Nullable(Of Date)
    Public Property descripcionSol As String
    Public Property fechaHoraInicio As Nullable(Of Date)
    Public Property fechaHoraFin As Nullable(Of Date)
    Public Property idEmpleado As Nullable(Of Integer)

    Public Overridable Property Empleado As Empleado

End Class
