'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SolVacaciones
    Public Property idSolVacaciones As Integer
    Public Property fechaSol As Nullable(Of Date)
    Public Property descripcionSol As String
    Public Property idEmpleado As Integer

    Public Overridable Property Empleado As Empleado

End Class
